### ISSUE TITLE
Mapa mental

### ISSUE THREAD

**Issue by AmilkarVladimiR** [SistemasTecTlaxiaco/actividad-1-mapa-mental-AmilkarVladimiR#1]
[Mapa mental-Amilkar Vladimir.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-mapa-mental-AmilkarVladimiR/files/10689527/Mapa.mental-Amilkar.Vladimir.pdf)

**Comment by ang3-l32** [comment]
CALIFICACIÓN:20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
